void main() {
  print(countReverseTranslate("MACLEGTWEVWIFKLTIWEHFYFCPEGLMWNRRHYFTWCEQPVNTLWTWCIPSRHWDRQWLYSPLSCRFDCSFQKQHFSRLPYWSDMIWNEYMDGMLWTERIKENANEWGWAYNYLPLMKKVQEFVYGWVEVSRITSFSDFQYWKTEQKRGSESYYSMDDNMCSGYTKKFETESNTTMNTCLLCENSWKIDNTHAYDRPWKYRGNSNGWDTRRRVDLPEGQENYYRSETVATHRRGKCIMQSFHAAYSDANDAQAPLRSDDSIFADLYPIVWHQRDCCKMWGHPQDHCCTTIICYNPAPDYMTSNEVNLTQKWQHKHISECYTPVATNLLVHGRIDKTSYRLWGPLHYMDCRMTALYQPGDMHEGPNKAVEDEISPDLGDCFWQFLRQCTKWYNCATMGLEIRHFIEVPGALKLIPTDNYAACHCRDKKINCDMIHGPDGNGKAHAIRIPDYGGSSLIKAIPSVGGSYEQDNKDPLNISECKICCEPPITLTNFFFCCCHHVVVDRLPKEFGTQGPQRNFDEIKNQEQGFIAIRAIGWLLAACDNRGRYIGCSFVNFYLQPEVEMGPSHLEAFRECIDKLWVDIVAHRGAMSFDKAIDFLNATQETQQCNSTHKTSVQLYWTINFNLAEEFFVQTMYSDDKSPQHIDTLLIMYFCFNMHCTFHCTREGFQWNAYIMINFMFHWRWYPNTLEMTRGVRNDEPRMDCYKSACCTASTPWRMWYAYFWLLVRTWTRCYETYTALVPMLAENFWKRPWCIKSMQCDFHTQDSAAAYERNRINAFSMYLDFITMSPAMVVWYIHKWEYNTNTRNPYRWQRNTFQKIHELKAIRQYQIHYFGEKHNVMGDMKAWTVRHPWTCIIEPEWSYMLKIAFEWHIYPQDSRWKECWYGTTEWIDIFFPRVQMLDHNCFSWHCAARFEYRQCPLCRMSDRNFLSIKDLPRRKWSNNVRAGPPMWILLFEIFIIRNEHAIPFHCVLFVMEVSTLEVIRFYVMWTHQARRNFWF"));
}

dynamic countReverseTranslate(String proteinSeq) {
  Map<String, int> aminoAcidCounts = {
    'A': 4,
    'C': 2,
    'D': 2,
    'E': 2,
    'F': 2,
    'G': 4,
    'H': 2,
    'I': 3,
    'K': 2,
    'L': 6,
    'M': 1,
    'N': 2,
    'P': 4,
    'Q': 2,
    'R': 6,
    'S': 6,
    'Stop': 3,
    'T': 4,
    'V': 4,
    'W': 1,
    'Y': 2
  };
  var res = proteinSeq
      .split("")
      .map(
        (e) => aminoAcidCounts[e],
      )
      .toList()
    ..add(aminoAcidCounts['Stop']);
  return res.reduce((value, element) => value!*element!%1000000,);
}
